export const state = () => ({
    items: [
        {
            id: 'id-ac1',
            title: 'BETWEEN COMMON HUMANITY AND PARTIALITY: THE CHOGYE BUDDHIST CHAPLAINCY MANUAL OF THE SOUTH KOREAN MILITARY AND ITS RELEVANCE TO INTERNATIONAL HUMANITARIAN LAW',
            cover: require('../assets/contemporary-buddhism.png'),
            text: "The Chogye Order of Korean Buddhism (K. Chogye chong or Jogyejong 曹溪宗) compiled a booklet called <i>Kukkun pŏbyo chip </i>(Essential Buddhist Teachings for the Armed Forces, 國軍法要集,<i> EBTAF</i> hereafter), which is distributed in the military Buddhist temples (K. <i>kun sachal;</i> Ch. <i>jun sisha</i> 軍寺刹) of South Korea. This manual for Buddhist military personnel draws on Buddhist classical texts and teachings to provide them both with doctrinal and practical information, and guidance as well as litanies for chaplains to perform crucial rites such as funerals. At the same time the <i>EBTAF</i> contains some distinctively Korean Buddhist references and ideas, and combines them with elements of Korean nationalism. In this context, this article analyses (1) the ideal traits of Buddhist combatants suggested in the <i>EBTAF</i> and their compliance with international humanitarian law (IHL); (2) the conflicting values illustrated in the booklet between Buddhist soldiers’ religious aspirations to uphold common humanity and the partiality inherent in their governmental affiliation; and (3) a passage to resolve the disparity. While the <i>EBTAF</i> aligns with IHL principles, some parts of it reflect a tension between Buddhist aspirations for peace and the military necessities of the state. Though IHL is not explicitly mentioned in the <i>EBTAF</i>, there is potential for embedding education on mutually complementary Buddhist and IHL values into Korean military chaplaincy.",
            pdf: require('../assets/pdf-page.png')
        }]
});